# default setup, make necessary changes based on our project
services:
  db:
    image: postgres:14 # may change if using firebase instead
    env_file: .env
    expose:
      - '5432'
    volumes:
      - group-project:/var/lib/postgresql/data # will also change if using firebase
      - ./src/init_data:/docker-entrypoint-initdb.d # will also change if using firebase
  web:
    image: node:lts
    user: 'node'
    working_dir: /repository
    env_file: .env
    environment:
      - NODE_ENV=development
      - SESSION_SECRET=${SESSION_SECRET}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - ./:/repository
    command: 'npm run testandrun'

volumes:
  group-project:
